# Generated by Django 5.2.1 on 2025-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="is_booked",
        ),
        migrations.AlterField(
            model_name="bus",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="bus",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
